export const CREATE_ORDER_REQ = "CREATE_ORDER_REQ";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
